name: commerce

x-healthcheck: &healthcheck
  interval: 10s
  timeout: 5s
  retries: 3

services:
  api:
    container_name: api
    build:
      context: ../..
      dockerfile: ./etc/docker/api/Dockerfile
      args:
        DOTENV_CONFIG_PATH: ./etc/env/.env.docker
      no_cache: false
    ports:
      - '8000:8000'
    develop:
      watch:
        - action: rebuild
          path: ../../package.json
        - action: sync
          path: ../..
          target: /api
    env_file:
      - ../env/.env.docker
    healthcheck:
      <<: *healthcheck
      test: ./etc/docker/healthcheck/api.sh || exit 1
      interval: 60s

  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - '16379:6379'
    healthcheck:
      <<: *healthcheck
      test: redis-cli ping || exit 1

  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - ../env/.env.docker
    volumes:
      - ./healthcheck/postgres.sh:/healthcheck.sh
    healthcheck:
      <<: *healthcheck
      test: ./healthcheck.sh || exit 1
